version: "3.7"
services:
  # frontend:
  #   build:
  #     context: frontend
  #     dockerfile: Dockerfile
  #   tty: true
  #   ports:
  #   - 8383:80
  #   volumes:
  #   - "./frontend:/app"
  #   depends_on:
  #     - backend
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
    - 8000:8000
    volumes:
      - "./backend:/app"
    depends_on:
      - database
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=wwt
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    volumes:
    - db:/var/lib/mysql
volumes:
  db: